export interface User {
  id?: string; // It is generated by DB, hence it is optional
  uid?: string; // It is generated by DB, hence it is optional
  name: string;
  email: string;
  password: string;
  role: string;
}
